spring:
  application:
    #name: entity-upload-file
    name: amsac-tramite-api

#  datasource:
#    url: jdbc:sqlserver://docker-host:1433;databaseName=scs
#    username: USR_INTEGRADOR_VUCE
#    password: xxx
#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #MongoDB settings
  datasource:
    url: jdbc:sqlserver://${app.connectionSqlServer.host}:${app.connectionSqlServer.port};encrypt=true;trustServerCertificate=true;databaseName=amsac_tramite
    username: ${app.connectionSqlServer.user}
    password: ${app.connectionSqlServer.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    hikari:
      poolName: SpringBootJPAHikariTDD
      minimumIdle: 10
      maximumPoolSize: 30
      #idleTimeout: 120000
      idleTimeout: 30000
      connectionTimeout: 5000
      leakDetectionThreshold: 2100
      auto-commit: false
      maxLifetime: 40000

    jpa:
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.SQLServer2008Dialect
          connection:
            provider_disables_autocommit: true


      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.SQLServer2008Dialect
      show-sql: false
      generate-ddl: false

  servlet:
    multipart:
      #enabled: false
      # Threshold after which files are written to disk.
      #file-size-threshold: 2KB
      # Max file size.
      max-file-size: 900MB
      # Max Request Size
      max-request-size: 900MB

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
#        dialect: org.hibernate.dialect.SQLServer2008Dialect


server:
  port:
    8300
    #8280
  servlet:
    #context-path: /entity-vuce-middleware
    context-path: /amsac-tramite-especificacion

##Properties
app:
  api:
    error:
      internal_server_error: Ocurrió un error inesperado, por favor intente en breve.
      bad_request: Request no tiene la estructura adecuada, verifique la documentación y vuelva a intentar.
      resource_not_found: No se encontro recurso(s) para los parametros enviado(s) %s
      bad_request_no_id: Debe enviar ID para actalizar el recurso deseado.
      bad_request_id_save: No Debe enviar ID para el registro del recurso.

    #keycloak:
    #grant-type: password
    #url-create-user: http://keycloack:8080/admin/realms/app-realm/users
    #url: http://keycloack:8080/realms/app-realm/protocol/openid-connect/token
    #grant_type: client_credentials
    #client-secret: p4jNYSp2HTe04nIkGlHvTgfIJ46mmDgf
    #client-id: admin-cli


  connectionMongo:
    user: user-amsac-db
    password: "%40ms%40c2022"
    host: mongoservice
    #host: 190.119.248.141
    port: 57017
    #port: 55881

  connectionSqlServer:
    user: sa
    password: Amsac..2024
    #password: D@n1ella
    #host: localhost
    host: 198.150.0.182
    #host: sqlserverservice
    port: 1433
    #port: 55881
    
  ruta:
    adjuntos: tramite
    documento-firma-externo: tramite/file/documento-firma/externo/
    logo-firma: tramite/file/logo-firma/
  url:
    #seguridad: http://localhost:8480/amsac-seguridad
    #seguridad: http://amsac-security-api:8100/amsac-seguridad
    ##seguridad: https://gatewayapp.amsac.pe/auth/amsac-seguridad
    #seguridad: http://amsac-security-service:8200/auth/amsac-seguridad
    seguridad: http://localhost:8200/auth/amsac-seguridad
    #mail: http://localhost:8200
    #mail: http://amsac-mail-api:8100
    mail: https://gatewayapp.amsac.pe/amsac-mail
    #mail: http://190.119.248.132:8180/amsac-mail
    #linkTramite: https://std.amsac.pe/admin/login https://std.amsac.pe/admin/tramites-pendientes
    linkTramite: https://std.amsac.pe/admin/tramites-pendientes/
    scheduler: https://std.amsac.pe/admin/login
    enviarAcuseTramite: http://amsac-tramite-service:8200/tramites/enviar-acuse-tramite/%s

  field:
    asuntoDerivacion: "STD AMSAC - Expediente Asignado"
    asuntoDerivacionCopia: "STD AMSAC - Para su conocimiento"
    asuntoAtencionFueraPlazo: "STD AMSAC - Expediente Asignado - N° Trámite: "
    asuntoAcuseRecepcionTramite: "Acuse de Recibo N° Trámite "

## File Storage Properties
file:
  base-upload-dir: tramite/file

fixedDelay:
  evaluar-tramite-derivacion:
    milliseconds: 100000

cron:
  ##second, minute, hour, day, month, weekday. Month and weekday names can be given as the first three letters of the English names
  #vencimiento-documento: 0 0 00,12 * * *
  #* "0 0 * * * *" = the top of every hour of every day.
  #* "*/10 * * * * *" = every ten seconds.
  #* "0 0 8-10 * * *" = 8, 9 and 10 o'clock of every day.
  #* "0 0 8,10 * * *" = 8 and 10 o'clock of every day.
  #* "0 0/30 8-10 * * *" = 8:00, 8:30, 9:00, 9:30 and 10 o'clock every day.
  #* "0 0 9-17 * * MON-FRI" = on the hour nine-to-five weekdays
  #* "0 0 0 25 12 ?" = every Christmas Day at midnight
  evaluar-vencimiento-tramite-derivacion: 0 0 8 * * *

