spring:
  application:
    #name: entity-upload-file
    name: amsac-tramite-api

#  datasource:
#    url: jdbc:sqlserver://docker-host:1433;databaseName=scs
#    username: USR_INTEGRADOR_VUCE
#    password: xxx
#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #MongoDB settings
  data:
    mongodb:
      uri: "mongodb://${app.connectionMongo.user}:${app.connectionMongo.password}@${app.connectionMongo.host}:${app.connectionMongo.port}/amsac-tramite"


#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
#        dialect: org.hibernate.dialect.SQLServer2008Dialect


server:
  port:
    8100
  servlet:
    #context-path: /entity-vuce-middleware
    context-path: /amsac-tramite

##Properties
#app:
  #keycloak:
    #grant-type: password
    #url-create-user: http://keycloack:8080/admin/realms/app-realm/users
    #url: http://keycloack:8080/realms/app-realm/protocol/openid-connect/token
    #grant_type: client_credentials
    #client-secret: p4jNYSp2HTe04nIkGlHvTgfIJ46mmDgf
    #client-id: admin-cli


  connectionMongo:
    user: user-amsac-db
    password: "%40ms%40c2022"
    #password: vvc33#t1ty
    host: 190.119.248.132
    #host: 172.16.1.228
    port: 57017
    #port: 55025

  ruta:
    adjuntos: tramite

## File Storage Properties
file:
  base-upload-dir: amsac/file/tramite