spring:
  application:
    #name: entity-upload-file
    name: amsac-tramite-api

#  datasource:
#    url: jdbc:sqlserver://docker-host:1433;databaseName=scs
#    username: USR_INTEGRADOR_VUCE
#    password: xxx
#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #MongoDB settings
  data:
    mongodb:
      uri: "mongodb://${app.connectionMongo.user}:${app.connectionMongo.password}@${app.connectionMongo.host}:${app.connectionMongo.port}/amsac-tramite"

  servlet:
    multipart:
      #enabled: true
      # Threshold after which files are written to disk.
      #file-size-threshold: 2KB
      # Max file size.
      max-file-size: 900MB
      # Max Request Size
      max-request-size: 905MB

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
#        dialect: org.hibernate.dialect.SQLServer2008Dialect


server:
  port:
    8100
    #8280
  #servlet:
    #context-path: /entity-vuce-middleware
    #context-path: /amsac-tramite

##Properties
app:
  #keycloak:
    #grant-type: password
    #url-create-user: http://keycloack:8080/admin/realms/app-realm/users
    #url: http://keycloack:8080/realms/app-realm/protocol/openid-connect/token
    #grant_type: client_credentials
    #client-secret: p4jNYSp2HTe04nIkGlHvTgfIJ46mmDgf
    #client-id: admin-cli


  connectionMongo:
    user: user-amsac-db
    #password: Evelyn123
    password: "%40ms%40c2022"
    #password: vvc33#t1ty
    #host: localhost
    host: mongoservice
    #host: 190.119.248.132
    #host: 172.16.1.228
    #port: 27017
    port: 57017
    #port: 55025

  ruta:
    adjuntos: tramite
  url:
    #seguridad: http://localhost:8480/amsac-seguridad
    seguridad: http://amsac-security-api:8100/amsac-seguridad
    #seguridad: http://190.119.248.132:8180/amsac-seguridad
    #mail: http://localhost:8400
    mail: http://amsac-mail-api:8100
    linkTramite: http://tramitedocumentario.amsac.pe/

## File Storage Properties
file:
  base-upload-dir: tramite/file

fixedDelay:
  evaluar-tramite-derivacion:
    milliseconds: 100000